

name: python app release

on:
  push:
    tags: 
      - 'v*'  
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Pillow
          pip install -r requirements.txt
      - name: Build with PyInstaller
        run: pyinstaller Code/gui.py --onefile --noconsole --name "MEDS pdf Editor" --ico="mdes.ico"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-dist-${{ matrix.os }}
          path: dist/*
  release:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            app-dist-ubuntu-latest/"MEDS pdf Editor"*
            app-dist-windows-latest/"MEDS pdf Editor"*
            app-dist-macos-latest/"MEDS pdf Editor"*
          body: |
            A new release of the application.
            - This release includes executables for Windows, macOS, and Linux.
          
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
